# Pandas

## Pandas Series

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
series = pd.Series([1,2,3,4])
type(series)

pandas.core.series.Series

In [4]:
series.axes

[RangeIndex(start=0, stop=4, step=1)]

In [5]:
series.dtype

dtype('int64')

In [6]:
series.empty

False

In [7]:
series.ndim

1

In [8]:
series.size

4

In [9]:
series.values

array([1, 2, 3, 4], dtype=int64)

In [10]:
series[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
series.head(2)

0    1
1    2
dtype: int64

In [12]:
series.tail(2)

2    3
3    4
dtype: int64

In [13]:
a=np.array([1,2,3,55,77,888])
a

array([  1,   2,   3,  55,  77, 888])

In [14]:
series = pd.Series(a)
series

0      1
1      2
2      3
3     55
4     77
5    888
dtype: int32

In [15]:
series.index

RangeIndex(start=0, stop=6, step=1)

In [16]:
pd.Series([1,5,0.8,34], index=[1,3,5,7])

1     1.0
3     5.0
5     0.8
7    34.0
dtype: float64

In [17]:
series = pd.Series([1,2,3,66,88,9,0.3], index=['a','b','c','d','e','f','g'])

In [18]:
series['g']

0.3

In [19]:
dictionary = {'reg':10, 'log':11, 'cart':12}
dictionary

{'reg': 10, 'log': 11, 'cart': 12}

In [20]:
series =pd.Series(dictionary)

In [21]:
series['reg']

10

In [22]:
series['log':'cart']

log     11
cart    12
dtype: int64

In [23]:
pd.concat([series,series])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [24]:
series.append(series)

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [25]:
series

reg     10
log     11
cart    12
dtype: int64

## Index Operations

In [26]:
series = pd.Series([1,2,3,4,5,66,77])
series

0     1
1     2
2     3
3     4
4     5
5    66
6    77
dtype: int64

In [27]:
series.keys

<bound method Series.keys of 0     1
1     2
2     3
3     4
4     5
5    66
6    77
dtype: int64>

In [28]:
list(series.items())

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 66), (6, 77)]

In [29]:
series.values

array([ 1,  2,  3,  4,  5, 66, 77], dtype=int64)

In [30]:
5 in series

True

In [31]:
series[[4,5]]

4     5
5    66
dtype: int64

In [32]:
series =pd.Series(dictionary)
series

reg     10
log     11
cart    12
dtype: int64

In [33]:
series['reg':'cart']

reg     10
log     11
cart    12
dtype: int64

In [34]:
series[(series>10) & (series<12)]

log    11
dtype: int64

In [35]:
data = pd.Series(['a','b','c'], index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [36]:
data[1] # data[0] will gives error

'a'

In [37]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [38]:
data.loc[5]

'c'

In [39]:
data.loc[0:4] # label based indexing location

1    a
3    b
dtype: object

In [40]:
data.iloc[0] # positional indexing, iloc , catch by resetting index

'a'

## Pandas Dataframe

In [41]:
l = [1,4,577,343]
l

[1, 4, 577, 343]

In [42]:
data = pd.DataFrame(l, columns=['values'])
type(data)

pandas.core.frame.DataFrame

In [43]:
data.axes

[RangeIndex(start=0, stop=4, step=1), Index(['values'], dtype='object')]

In [44]:
data.shape

(4, 1)

In [45]:
data.ndim

2

In [46]:
data.values

array([[  1],
       [  4],
       [577],
       [343]], dtype=int64)

In [47]:
data.head(2)

values
0       1
1       4

In [48]:
data.tail(2)

values
2     577
3     343

In [49]:
a=np.array([1,2,3,4,566])
type(a)

numpy.ndarray

In [50]:
pd.DataFrame(a,columns=['values'])

values
0       1
1       2
2       3
3       4
4     566

In [51]:
v = np.arange(1,10).reshape(3,3)
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
data=pd.DataFrame(v,columns=['v1','v2','v3'])
data

v1  v2  v3
0   1   2   3
1   4   5   6
2   7   8   9

In [53]:
data.columns=('value1','value2','value3')
data

value1  value2  value3
0       1       2       3
1       4       5       6
2       7       8       9

In [54]:
data=pd.DataFrame(v,columns=['v1','v2','v3'], index=['a','b','c'])
data

v1  v2  v3
a   1   2   3
b   4   5   6
c   7   8   9

In [55]:
pd.DataFrame(pd.Series([1,2,3,4]),columns=['variable'])

variable
0         1
1         2
2         3
3         4

In [56]:
a = pd.Series([1,2,3,4])
b = pd.Series([1,2,3,4])

In [57]:
pd.DataFrame({'variable1':a,
              'variable2':b})

variable1  variable2
0          1          1
1          2          2
2          3          3
3          4          4

In [58]:
dict_ = {
    'reg':{'RMSE':101,
           'MSE':111,
           'SSE':121},
    'log':{'RMSE':102,
           'MSE':112,
           'SSE':122},
    'cart':{'RMSE':103,
           'MSE':113,
           'SSE':123},
}

In [59]:
pd.DataFrame(dict_)

reg  log  cart
RMSE  101  102   103
MSE   111  112   113
SSE   121  122   123

In [60]:
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size=5)
s3 = np.random.randint(10,size=5)
df = pd.DataFrame({'var1':s1,'var2':s2,'var3':s3})
df

var1  var2  var3
0     1     2     9
1     2     3     0
2     0     7     8
3     9     8     4
4     6     7     6

In [61]:
df[0:1]

var1  var2  var3
0     1     2     9

In [62]:
df.index=['a','b','c','d','e']

In [63]:
df['c':'e']

var1  var2  var3
c     0     7     8
d     9     8     4
e     6     7     6

In [64]:
df.drop('a', axis=0, inplace=True)

In [65]:
df

var1  var2  var3
b     2     3     0
c     0     7     8
d     9     8     4
e     6     7     6

In [66]:
l = ['b','c']

In [67]:
l

['b', 'c']

In [68]:
df.drop(l,axis=0)

var1  var2  var3
d     9     8     4
e     6     7     6

In [69]:
'var1' in df

True

In [70]:
l = ['var1','var2','var7']

In [71]:
for i in l:
    print(i in df)

True
True
False


In [72]:
df['var1'] is df['var2']

False

In [73]:
df['var1'] # dictionary type choice

b    2
c    0
d    9
e    6
Name: var1, dtype: int32

In [74]:
df.var1 # attribute type choice

b    2
c    0
d    9
e    6
Name: var1, dtype: int32

In [75]:
df[['var1','var2']]

var1  var2
b     2     3
c     0     7
d     9     8
e     6     7

In [76]:
l = ['var1','var2']
df[l]

var1  var2
b     2     3
c     0     7
d     9     8
e     6     7

In [77]:
df['added_column'] = df['var1'] / df['var2']
df

var1  var2  var3  added_column
b     2     3     0      0.666667
c     0     7     8      0.000000
d     9     8     4      1.125000
e     6     7     6      0.857143

In [78]:
df.drop('c',axis=0, inplace=True)

In [79]:
df

var1  var2  var3  added_column
b     2     3     0      0.666667
d     9     8     4      1.125000
e     6     7     6      0.857143

In [80]:
df.drop('var1', axis=1, inplace=True)

In [81]:
df

var2  var3  added_column
b     3     0      0.666667
d     8     4      1.125000
e     7     6      0.857143

## Reach to observations and variables

In [82]:
df

var2  var3  added_column
b     3     0      0.666667
d     8     4      1.125000
e     7     6      0.857143

In [83]:
df.iloc[:3]

var2  var3  added_column
b     3     0      0.666667
d     8     4      1.125000
e     7     6      0.857143

In [84]:
df.iloc[:2, :2]

var2  var3
b     3     0
d     8     4

In [85]:
df['var3']

b    0
d    4
e    6
Name: var3, dtype: int32

In [86]:
df.loc[:'e', 'var3']

b    0
d    4
e    6
Name: var3, dtype: int32

In [87]:
df[df.var3 > 4]['var2']

e    7
Name: var2, dtype: int32

In [88]:
df[(df.var3 > 3 & (df.var3 < 2))]['var2'] # conditional index operations

d    8
e    7
Name: var2, dtype: int32

In [89]:
df.loc[df.var2 > 3, ['added_column']]

added_column
d      1.125000
e      0.857143

## Merge - Join Operations

In [90]:
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size=5)
s3 = np.random.randint(10,size=5)
df = pd.DataFrame({'var1':s1,'var2':s2,'var3':s3})
df

var1  var2  var3
0     5     7     6
1     4     6     4
2     3     5     6
3     3     7     3
4     0     3     7

In [91]:
df2 = df+99
df2

var1  var2  var3
0   104   106   105
1   103   105   103
2   102   104   105
3   102   106   102
4    99   102   106

In [92]:
pd.concat([df,df2], axis=0)

var1  var2  var3
0     5     7     6
1     4     6     4
2     3     5     6
3     3     7     3
4     0     3     7
0   104   106   105
1   103   105   103
2   102   104   105
3   102   106   102
4    99   102   106

In [93]:
pd.concat([df,df2], axis=0, ignore_index=True)

var1  var2  var3
0     5     7     6
1     4     6     4
2     3     5     6
3     3     7     3
4     0     3     7
5   104   106   105
6   103   105   103
7   102   104   105
8   102   106   102
9    99   102   106

In [94]:
df2.columns= ['var1','var2','v3']
df2

var1  var2   v3
0   104   106  105
1   103   105  103
2   102   104  105
3   102   106  102
4    99   102  106

In [95]:
pd.concat([df,df2], axis=0, ignore_index=True)

C:\Users\berka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


v3  var1  var2  var3
0    NaN     5     7   6.0
1    NaN     4     6   4.0
2    NaN     3     5   6.0
3    NaN     3     7   3.0
4    NaN     0     3   7.0
5  105.0   104   106   NaN
6  103.0   103   105   NaN
7  105.0   102   104   NaN
8  102.0   102   106   NaN
9  106.0    99   102   NaN

In [96]:
pd.concat([df,df2], axis=0, join='inner')

var1  var2
0     5     7
1     4     6
2     3     5
3     3     7
4     0     3
0   104   106
1   103   105
2   102   104
3   102   106
4    99   102

In [97]:
pd.concat([df,df2], join_axes=[df.columns])

C:\Users\berka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


var1  var2  var3
0     5     7   6.0
1     4     6   4.0
2     3     5   6.0
3     3     7   3.0
4     0     3   7.0
0   104   106   NaN
1   103   105   NaN
2   102   104   NaN
3   102   106   NaN
4    99   102   NaN

In [98]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [99]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [100]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [101]:
pd.merge(df1, df2, on = 'calisanlar')

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [102]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [103]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [104]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [105]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [106]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [107]:
pd.merge(df3,df5)

calisanlar         grup  ilk_giris yetenekler
0        Ali     Muhasebe       2009  matematik
1        Ali     Muhasebe       2009      excel
2       Veli  Muhendislik       2014    kodlama
3       Veli  Muhendislik       2014      linux
4       Ayse  Muhendislik       2010    kodlama
5       Ayse  Muhendislik       2010      linux
6      Fatma           İK       2019      excel
7      Fatma           İK       2019    yonetim

In [108]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [109]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [110]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

In [111]:
df3 = pd.DataFrame({'name': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'maas': [70000, 80000, 120000, 90000]})

df3

name    maas
0    Ali   70000
1   Veli   80000
2   Ayse  120000
3  Fatma   90000

In [112]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [113]:
pd.merge(df1,df3, left_on='calisanlar', right_on='name').drop('calisanlar', axis=1)

grup   name    maas
0     Muhasebe    Ali   70000
1  Muhendislik   Veli   80000
2  Muhendislik   Ayse  120000
3           İK  Fatma   90000

In [114]:
df3a = df3.set_index('name')
df3a

maas
name         
Ali     70000
Veli    80000
Ayse   120000
Fatma   90000

In [115]:
df3a.shape

(4, 1)

In [116]:
df2a = df2.set_index('calisanlar')
df2a

ilk_giris
calisanlar           
Ayse             2010
Ali              2009
Veli             2014
Fatma            2019

In [117]:
pd.merge(df3a, df2a, left_index=True, right_index=True) # intersection df3a<>df2a (there is none)

maas  ilk_giris
Ali     70000       2009
Veli    80000       2014
Ayse   120000       2010
Fatma   90000       2019

In [118]:
df3a.join(df2a)

maas  ilk_giris
name                    
Ali     70000       2009
Veli    80000       2014
Ayse   120000       2010
Fatma   90000       2019

In [119]:
dfa = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'siralama': [1, 2, 3, 4]})

dfa

calisanlar  siralama
0        Ali         1
1       Veli         2
2       Ayse         3
3      Fatma         4

In [120]:
dfb = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'siralama': [3, 1, 4, 2]})

dfb

calisanlar  siralama
0        Ali         3
1       Veli         1
2       Ayse         4
3      Fatma         2

In [121]:
pd.merge(dfa, dfb, on = 'calisanlar')

calisanlar  siralama_x  siralama_y
0        Ali           1           3
1       Veli           2           1
2       Ayse           3           4
3      Fatma           4           2

In [122]:
pd.merge(dfa, dfb, on = 'calisanlar', suffixes=['Salary','Experience'])

calisanlar  siralamaSalary  siralamaExperience
0        Ali               1                   3
1       Veli               2                   1
2       Ayse               3                   4
3      Fatma               4                   2

## Aggregation and Grouping Operations

In [123]:
df = sns.load_dataset('planets')

In [124]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [125]:
df.shape

(1035, 6)

In [126]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [127]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [128]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [129]:
df.groupby('gruplar').sum()

veri
gruplar      
A          33
B          54
C         107

In [130]:
df = sns.load_dataset('planets')

In [131]:
df.groupby('method')['orbital_period'].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [132]:
df.groupby('method')['orbital_period'].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

## Aggregate, filter, transform, apply

In [133]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [135]:
df.groupby('gruplar').aggregate([min, np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [138]:
df.groupby('gruplar').aggregate({'degisken1': min, 'degisken2': max})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [154]:
def filter_func(x):
    return x['degisken1'].std() > 9.5

In [155]:
df.groupby('gruplar').filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [156]:
df.groupby('gruplar').transform(lambda x:x-x.mean())

degisken1  degisken2
0       -6.0      -81.0
1        6.0       71.0
2      -33.0     -318.0
3        6.0       81.0
4       -6.0      -71.0
5       33.0      318.0

In [157]:
df.groupby('gruplar').apply(np.sum)

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [158]:
df.groupby('gruplar').apply(np.mean)

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [159]:
L = [0,1,0,1,2,0]

In [160]:
df.groupby(L).sum()

degisken1  degisken2
0        142       1402
1         45        515
2         11        111