# Pandas

## Pandas Series

In [3]:
import numpy as np
import pandas as pd

In [5]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
series = pd.Series([1,2,3,4])
type(series)

pandas.core.series.Series

In [9]:
series.axes

[RangeIndex(start=0, stop=4, step=1)]

In [10]:
series.dtype

dtype('int64')

In [11]:
series.empty

False

In [12]:
series.ndim

1

In [13]:
series.size

4

In [14]:
series.values

array([1, 2, 3, 4], dtype=int64)

In [23]:
series[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [25]:
series.head(2)

0    1
1    2
dtype: int64

In [27]:
series.tail(2)

2    3
3    4
dtype: int64

In [31]:
a=np.array([1,2,3,55,77,888])
a

array([  1,   2,   3,  55,  77, 888])

In [35]:
series = pd.Series(a)
series

0      1
1      2
2      3
3     55
4     77
5    888
dtype: int32

In [37]:
series.index

RangeIndex(start=0, stop=6, step=1)

In [39]:
pd.Series([1,5,0.8,34], index=[1,3,5,7])

1     1.0
3     5.0
5     0.8
7    34.0
dtype: float64

In [43]:
series = pd.Series([1,2,3,66,88,9,0.3], index=['a','b','c','d','e','f','g'])

In [46]:
series['g']

0.3

In [47]:
dictionary = {'reg':10, 'log':11, 'cart':12}
dictionary

{'reg': 10, 'log': 11, 'cart': 12}

In [50]:
series =pd.Series(dictionary)

In [52]:
series['reg']

10

In [54]:
series['log':'cart']

log     11
cart    12
dtype: int64

In [56]:
pd.concat([series,series])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [59]:
series.append(series)

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [61]:
series

reg     10
log     11
cart    12
dtype: int64

## Index Operations

In [63]:
series = pd.Series([1,2,3,4,5,66,77])
series

0     1
1     2
2     3
3     4
4     5
5    66
6    77
dtype: int64

In [65]:
series.keys

<bound method Series.keys of 0     1
1     2
2     3
3     4
4     5
5    66
6    77
dtype: int64>

In [68]:
list(series.items())

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 66), (6, 77)]

In [70]:
series.values

array([ 1,  2,  3,  4,  5, 66, 77], dtype=int64)

In [72]:
5 in series

True

In [75]:
series[[4,5]]

4     5
5    66
dtype: int64

In [79]:
series =pd.Series(dictionary)
series

reg     10
log     11
cart    12
dtype: int64

In [81]:
series['reg':'cart']

reg     10
log     11
cart    12
dtype: int64

In [84]:
series[(series>10) & (series<12)]

log    11
dtype: int64

In [88]:
data = pd.Series(['a','b','c'], index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [90]:
data[1] # data[0] will gives error

'a'

In [98]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [101]:
data.loc[5]

'c'

In [111]:
data.loc[0:4] # label based indexing location

1    a
3    b
dtype: object

In [112]:
data.iloc[0] # positional indexing, iloc , catch by resetting index

'a'