In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])

a*b

array([ 1,  6, 15, 28])

In [4]:
who # shows variables

No variables match your requested type.


# NumPy Arrays

In [5]:
a = np.array([2.6,3.11,58,22,2,5])
type(a)

numpy.ndarray

In [6]:
np.array([2.6,3.,66.7,58,22,2,5], dtype = 'float32')

array([ 2.6,  3. , 66.7, 58. , 22. ,  2. ,  5. ], dtype=float32)

In [7]:
np.zeros(20, dtype=int) # creates an array consisting 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((2,4)) # creates a matris consisting 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((3,3),8) # creates a matris consisting what I gave

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [12]:
np.random.normal(0,1,(3,4))

array([[ 0.24309371, -0.11393726,  0.80341487,  0.04278247],
       [-0.10545393, -0.43504958,  1.74878214,  0.69383172],
       [-1.61523489, -1.20916469, -1.10863947, -0.66221605]])

In [13]:
np.random.randint(0,10, (3,3))

array([[6, 6, 0],
       [4, 5, 6],
       [3, 8, 6]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Forming (Shape Operations)

In [15]:
a = np.random.randint(0,10, (3,3))
a

array([[1, 7, 3],
       [3, 9, 4],
       [5, 3, 9]])

In [16]:
a = np.random.randint(0,10, (3,3))
a

array([[2, 0, 7],
       [0, 7, 7],
       [1, 4, 6]])

In [17]:
a.shape

(3, 3)

In [18]:
a.ndim # size

2

In [19]:
a = np.random.randint(0,10, (3,3,3))
a

array([[[0, 0, 2],
        [8, 1, 1],
        [7, 9, 4]],

       [[4, 4, 4],
        [8, 3, 5],
        [9, 5, 5]],

       [[9, 2, 3],
        [9, 6, 6],
        [9, 8, 4]]])

In [20]:
a.shape

(3, 3, 3)

In [21]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a = np.array([1,2,3])
b = a.reshape((1,3))

In [23]:
a.ndim

1

In [24]:
b.ndim

2

In [25]:
a[np.newaxis, :] # reshaped 1d array to 2d (vector) - matrix

array([[1, 2, 3]])

In [26]:
a[:,np.newaxis] # column vector

array([[1],
       [2],
       [3]])

## Array Concatenate

In [39]:
b = np.array([4,5,6])

In [41]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [45]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
y = np.arange(10,19).reshape((3,3))
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [50]:
np.concatenate([x,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [54]:
np.concatenate([x,y], axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [56]:
a

array([1, 2, 3])

In [58]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.vstack([a,x]) # vertical stack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [75]:
np.hstack([a.reshape(-1,1),x])

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

## Array Split Operations

In [79]:
z = [1,2,3,55,78,99,111,55]
np.split(z,[3,5])

[array([1, 2, 3]), array([55, 78]), array([ 99, 111,  55])]

In [82]:
t = np.arange(16).reshape((4,4))
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
top,bot = np.vsplit(t,[2])

In [87]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
bot

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
left,right = np.hsplit(t,[2])

In [93]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [95]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sorting

In [102]:
complexlist = np.array([2,5,34,566,11,55,22])

In [103]:
np.sort(complexlist)

array([  2,   5,  11,  22,  34,  55, 566])

In [108]:
i = np.argsort(complexlist) # we uses argsort for to observe index change
i

array([0, 1, 4, 6, 2, 5, 3], dtype=int64)

In [109]:
complexlist[i]

array([  2,   5,  11,  22,  34,  55, 566])