In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])

a*b

array([ 1,  6, 15, 28])

In [3]:
who # shows variables

No variables match your requested type.


# NumPy Arrays

In [4]:
a = np.array([2.6,3.11,58,22,2,5])
type(a)

numpy.ndarray

In [5]:
np.array([2.6,3.,66.7,58,22,2,5], dtype = 'float32')

array([ 2.6,  3. , 66.7, 58. , 22. ,  2. ,  5. ], dtype=float32)

In [6]:
np.zeros(20, dtype=int) # creates an array consisting 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((2,4)) # creates a matris consisting 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((3,3),8) # creates a matris consisting what I gave

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [11]:
np.random.normal(0,1,(3,4))

array([[-0.10940073, -1.94028349,  1.79512587, -0.61343023],
       [ 1.20497213,  0.33877154,  0.42845925,  0.52231696],
       [-0.6126029 ,  1.03174617, -2.64098581, -1.34941585]])

In [12]:
np.random.randint(0,10, (3,3))

array([[8, 9, 7],
       [7, 4, 4],
       [4, 6, 3]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Forming (Shape Operations)

In [14]:
a = np.random.randint(0,10, (3,3))
a

array([[5, 5, 1],
       [3, 1, 8],
       [7, 6, 2]])

In [15]:
a = np.random.randint(0,10, (3,3))
a

array([[0, 1, 0],
       [1, 6, 4],
       [6, 8, 2]])

In [16]:
a.shape

(3, 3)

In [17]:
a.ndim # size

2

In [18]:
a = np.random.randint(0,10, (3,3,3))
a

array([[[3, 9, 2],
        [4, 9, 5],
        [6, 1, 8]],

       [[0, 1, 3],
        [3, 9, 6],
        [6, 1, 1]],

       [[6, 6, 8],
        [1, 4, 8],
        [0, 6, 2]]])

In [19]:
a.shape

(3, 3, 3)

In [20]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a = np.array([1,2,3])
b = a.reshape((1,3))

In [22]:
a.ndim

1

In [23]:
b.ndim

2

In [24]:
a[np.newaxis, :] # reshaped 1d array to 2d (vector) - matrix

array([[1, 2, 3]])

In [25]:
a[:,np.newaxis] # column vector

array([[1],
       [2],
       [3]])

## Array Concatenate

In [26]:
b = np.array([4,5,6])

In [27]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [28]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y = np.arange(10,19).reshape((3,3))
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [30]:
np.concatenate([x,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
np.concatenate([x,y], axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [32]:
a

array([1, 2, 3])

In [33]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.vstack([a,x]) # vertical stack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [36]:
np.hstack([a.reshape(-1,1),x])

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

## Array Split Operations

In [37]:
z = [1,2,3,55,78,99,111,55]
np.split(z,[3,5])

[array([1, 2, 3]), array([55, 78]), array([ 99, 111,  55])]

In [38]:
t = np.arange(16).reshape((4,4))
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
top,bot = np.vsplit(t,[2])

In [40]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
bot

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
left,right = np.hsplit(t,[2])

In [43]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [44]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sorting

In [45]:
complexlist = np.array([2,5,34,566,11,55,22])

In [46]:
np.sort(complexlist)

array([  2,   5,  11,  22,  34,  55, 566])

In [47]:
i = np.argsort(complexlist) # we uses argsort for to observe index change
i

array([0, 1, 4, 6, 2, 5, 3], dtype=int64)

In [48]:
complexlist[i]

array([  2,   5,  11,  22,  34,  55, 566])

## Numpy Index and Slice Operations

In [49]:
a = np.random.randint(10, size=10)
a

array([3, 2, 4, 0, 0, 7, 1, 6, 0, 9])

In [50]:
a[0]

3

In [51]:
a[-2]

0

In [52]:
a[-2] = 2

In [53]:
a[-2]

2

In [54]:
a = np.random.randint(10, size=(4,4))
a

array([[0, 8, 3, 3],
       [4, 2, 0, 9],
       [4, 4, 4, 5],
       [0, 0, 2, 7]])

In [55]:
a[1,3]

9

In [56]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
a[0:4]

array([1, 2, 3, 4])

In [58]:
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
a[2:5]

array([3, 4, 5])

In [60]:
a[0::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [61]:
a[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
a = np.random.randint(10, size=(5,5))
a

array([[0, 7, 4, 2, 7],
       [7, 7, 6, 6, 6],
       [1, 6, 4, 0, 3],
       [4, 7, 2, 5, 0],
       [4, 8, 9, 3, 3]])

In [63]:
a[:,0] # all rows, 0(index) column

array([0, 7, 1, 4, 4])

In [67]:
a[0:3]

array([[0, 7, 4, 2, 7],
       [7, 7, 6, 6, 6],
       [1, 6, 4, 0, 3]])

In [69]:
a

array([[0, 7, 4, 2, 7],
       [7, 7, 6, 6, 6],
       [1, 6, 4, 0, 3],
       [4, 7, 2, 5, 0],
       [4, 8, 9, 3, 3]])

In [70]:
a[:2,:3]

array([[0, 7, 4],
       [7, 7, 6]])

In [72]:
a[:,:2]

array([[0, 7],
       [7, 7],
       [1, 6],
       [4, 7],
       [4, 8]])

In [74]:
a = np.random.randint(10, size=(5,5))
a

array([[7, 0, 2, 8, 2],
       [3, 6, 1, 8, 5],
       [7, 5, 6, 9, 9],
       [4, 4, 5, 0, 5],
       [2, 4, 3, 2, 7]])

In [76]:
sub_a =a[0:3,0:2] # dependent subset
sub_a

array([[7, 0],
       [3, 6],
       [7, 5]])

In [82]:
sub_a[0,0],sub_a[1,1],sub_a[2,1] = 9999,9999,9999
sub_a

array([[9999,    0],
       [   3, 9999],
       [   7, 9999]])

In [84]:
a

array([[9999,    0,    2,    8,    2],
       [   3, 9999,    1,    8,    5],
       [   7, 9999,    6,    9,    9],
       [   4,    4,    5,    0,    5],
       [   2,    4,    3,    2,    7]])

In [85]:
a = np.random.randint(10, size=(5,5))
a

array([[3, 3, 5, 7, 1],
       [9, 7, 6, 4, 9],
       [5, 6, 4, 4, 8],
       [4, 4, 3, 8, 0],
       [7, 1, 6, 4, 2]])

In [86]:
sub_a =a[0:3,0:2].copy() # independent subset
sub_a

array([[3, 3],
       [9, 7],
       [5, 6]])

In [87]:
sub_a[0,0],sub_a[1,1],sub_a[2,1] = 9999,9999,9999
sub_a

array([[9999,    3],
       [   9, 9999],
       [   5, 9999]])

In [89]:
a

array([[3, 3, 5, 7, 1],
       [9, 7, 6, 4, 9],
       [5, 6, 4, 4, 8],
       [4, 4, 3, 8, 0],
       [7, 1, 6, 4, 2]])

## Index Operations with Fancy Index

In [91]:
v = np.arange(0,31,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [95]:
take = [1,3,5]
v[take]

array([ 3,  9, 15])

In [101]:
vec = np.arange(9).reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
row = np.array([0,1])
col = np.array([1,2])

In [104]:
vec[row,col]

array([1, 5])

In [106]:
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
vec[0,[1,2]]

array([1, 2])

In [109]:
vec[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [110]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [112]:
v[index] = 99
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [115]:
v[[0,1]] = [4,6]
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])