In [157]:
import numpy as np

In [158]:
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])

a*b

array([ 1,  6, 15, 28])

In [159]:
who # shows variables

No variables match your requested type.


# NumPy Arrays

In [160]:
a = np.array([2.6,3.11,58,22,2,5])
type(a)

numpy.ndarray

In [161]:
np.array([2.6,3.,66.7,58,22,2,5], dtype = 'float32')

array([ 2.6,  3. , 66.7, 58. , 22. ,  2. ,  5. ], dtype=float32)

In [162]:
np.zeros(20, dtype=int) # creates an array consisting 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [163]:
np.ones((2,4)) # creates a matris consisting 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [164]:
np.full((3,3),8) # creates a matris consisting what I gave

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [165]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [166]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [167]:
np.random.normal(0,1,(3,4))

array([[ 0.13457195, -0.19857613, -1.86322063, -1.90726457],
       [-1.23783462,  0.63970972, -0.19726644, -1.32439071],
       [ 0.22973784, -1.47102221,  1.68538043,  0.96156519]])

In [168]:
np.random.randint(0,10, (3,3))

array([[7, 4, 8],
       [3, 1, 7],
       [3, 7, 8]])

In [169]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Forming (Shape Operations)

In [170]:
a = np.random.randint(0,10, (3,3))
a

array([[3, 8, 1],
       [2, 3, 7],
       [0, 0, 8]])

In [171]:
a = np.random.randint(0,10, (3,3))
a

array([[6, 3, 1],
       [4, 2, 7],
       [2, 7, 7]])

In [172]:
a.shape

(3, 3)

In [173]:
a.ndim # size

2

In [174]:
a = np.random.randint(0,10, (3,3,3))
a

array([[[0, 1, 6],
        [7, 1, 7],
        [1, 4, 3]],

       [[7, 0, 7],
        [1, 2, 6],
        [6, 1, 1]],

       [[2, 6, 9],
        [2, 1, 6],
        [5, 8, 2]]])

In [175]:
a.shape

(3, 3, 3)

In [176]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
a = np.array([1,2,3])
b = a.reshape((1,3))

In [178]:
a.ndim

1

In [179]:
b.ndim

2

In [180]:
a[np.newaxis, :] # reshaped 1d array to 2d (vector) - matrix

array([[1, 2, 3]])

In [181]:
a[:,np.newaxis] # column vector

array([[1],
       [2],
       [3]])

## Array Concatenate

In [182]:
b = np.array([4,5,6])

In [183]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [184]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
y = np.arange(10,19).reshape((3,3))
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [186]:
np.concatenate([x,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [187]:
np.concatenate([x,y], axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [188]:
a

array([1, 2, 3])

In [189]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [190]:
np.vstack([a,x]) # vertical stack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [192]:
np.hstack([a.reshape(-1,1),x])

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

## Array Split Operations

In [193]:
z = [1,2,3,55,78,99,111,55]
np.split(z,[3,5])

[array([1, 2, 3]), array([55, 78]), array([ 99, 111,  55])]

In [194]:
t = np.arange(16).reshape((4,4))
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
top,bot = np.vsplit(t,[2])

In [196]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [197]:
bot

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [198]:
left,right = np.hsplit(t,[2])

In [199]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [200]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sorting

In [201]:
complexlist = np.array([2,5,34,566,11,55,22])

In [202]:
np.sort(complexlist)

array([  2,   5,  11,  22,  34,  55, 566])

In [203]:
i = np.argsort(complexlist) # we uses argsort for to observe index change
i

array([0, 1, 4, 6, 2, 5, 3], dtype=int64)

In [204]:
complexlist[i]

array([  2,   5,  11,  22,  34,  55, 566])

## Numpy Index and Slice Operations

In [205]:
a = np.random.randint(10, size=10)
a

array([6, 3, 5, 2, 5, 6, 8, 5, 7, 8])

In [206]:
a[0]

6

In [207]:
a[-2]

7

In [208]:
a[-2] = 2

In [209]:
a[-2]

2

In [210]:
a = np.random.randint(10, size=(4,4))
a

array([[4, 6, 9, 3],
       [4, 9, 5, 3],
       [0, 9, 5, 7],
       [8, 6, 3, 6]])

In [211]:
a[1,3]

3

In [212]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [213]:
a[0:4]

array([1, 2, 3, 4])

In [214]:
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [215]:
a[2:5]

array([3, 4, 5])

In [216]:
a[0::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [217]:
a[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [218]:
a = np.random.randint(10, size=(5,5))
a

array([[3, 9, 1, 2, 1],
       [2, 8, 6, 6, 3],
       [3, 7, 0, 9, 4],
       [6, 6, 2, 5, 5],
       [0, 2, 2, 5, 3]])

In [219]:
a[:,0] # all rows, 0(index) column

array([3, 2, 3, 6, 0])

In [220]:
a[0:3]

array([[3, 9, 1, 2, 1],
       [2, 8, 6, 6, 3],
       [3, 7, 0, 9, 4]])

In [221]:
a

array([[3, 9, 1, 2, 1],
       [2, 8, 6, 6, 3],
       [3, 7, 0, 9, 4],
       [6, 6, 2, 5, 5],
       [0, 2, 2, 5, 3]])

In [222]:
a[:2,:3]

array([[3, 9, 1],
       [2, 8, 6]])

In [223]:
a[:,:2]

array([[3, 9],
       [2, 8],
       [3, 7],
       [6, 6],
       [0, 2]])

In [224]:
a = np.random.randint(10, size=(5,5))
a

array([[5, 3, 0, 0, 2],
       [0, 5, 1, 0, 7],
       [3, 5, 2, 6, 9],
       [9, 6, 2, 2, 0],
       [2, 5, 0, 3, 1]])

In [225]:
sub_a =a[0:3,0:2] # dependent subset
sub_a

array([[5, 3],
       [0, 5],
       [3, 5]])

In [226]:
sub_a[0,0],sub_a[1,1],sub_a[2,1] = 9999,9999,9999
sub_a

array([[9999,    3],
       [   0, 9999],
       [   3, 9999]])

In [227]:
a

array([[9999,    3,    0,    0,    2],
       [   0, 9999,    1,    0,    7],
       [   3, 9999,    2,    6,    9],
       [   9,    6,    2,    2,    0],
       [   2,    5,    0,    3,    1]])

In [228]:
a = np.random.randint(10, size=(5,5))
a

array([[3, 5, 8, 9, 0],
       [0, 0, 0, 8, 6],
       [2, 7, 7, 9, 1],
       [6, 3, 2, 2, 8],
       [1, 8, 8, 8, 4]])

In [229]:
sub_a =a[0:3,0:2].copy() # independent subset
sub_a

array([[3, 5],
       [0, 0],
       [2, 7]])

In [230]:
sub_a[0,0],sub_a[1,1],sub_a[2,1] = 9999,9999,9999
sub_a

array([[9999,    5],
       [   0, 9999],
       [   2, 9999]])

In [231]:
a

array([[3, 5, 8, 9, 0],
       [0, 0, 0, 8, 6],
       [2, 7, 7, 9, 1],
       [6, 3, 2, 2, 8],
       [1, 8, 8, 8, 4]])

## Index Operations with Fancy Index

In [232]:
v = np.arange(0,31,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [233]:
take = [1,3,5]
v[take]

array([ 3,  9, 15])

In [234]:
vec = np.arange(9).reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [235]:
row = np.array([0,1])
col = np.array([1,2])

In [236]:
vec[row,col]

array([1, 5])

In [237]:
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [238]:
vec[0,[1,2]]

array([1, 2])

In [239]:
vec[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [240]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [241]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [242]:
v[index] = 99
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [243]:
v[[0,1]] = [4,6]
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

## Conditional Index Operations

In [244]:
v = np.array([1,2,3,4,5])

In [245]:
v > 3

array([False, False, False,  True,  True])

In [246]:
v <= 3

array([ True,  True,  True, False, False])

In [247]:
v != 3

array([ True,  True, False,  True,  True])

In [248]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [249]:
(2*v) == (v**2) # ufunc operations

array([False,  True, False, False, False])

In [250]:
np.equal([0,1,3],np.arange(3))

array([ True,  True, False])

In [251]:
v = np.random.randint(0,10,(3,3))
v

array([[5, 9, 3],
       [0, 5, 1],
       [1, 9, 3]])

In [252]:
v>5

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [253]:
np.sum(v > 5) # 4 value are greater than five

2

In [254]:
np.sum((v>3) & (v<8)) # a value is between 3-8

2

In [255]:
np.sum((v>3) | (v<8)) # nine value are greater three or smaller eight

9

In [256]:
np.sum(v > 5, axis = 1)

array([1, 0, 1])

In [257]:
np.sum(v > 5, axis = 0)

array([0, 2, 0])

In [258]:
np.all(v > 3) # are all component greater three?

False

In [259]:
np.all(v >= 0)

True

In [260]:
np.any(v < 4) # is there any value lower than 4?

True

In [261]:
np.any(v < 4, axis = 1) # is there any values lower than 4 for rows

array([ True,  True,  True])

In [262]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [263]:
v[v > 2] # which components are greater than 2?

array([3, 4, 5])

In [264]:
v[(v>2) & (v<8)]

array([3, 4, 5])

In [265]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [266]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [267]:
a % 2

array([0, 1, 0, 1, 0], dtype=int32)

In [268]:
5 * ((a / 2) * 9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [269]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [270]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [271]:
np.divide(a,9)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444])

In [272]:
np.power(a,4)

array([  0,   1,  16,  81, 256], dtype=int32)

In [275]:
np.add.reduce(a)

10

In [276]:
np.add.accumulate(a)

array([ 0,  1,  3,  6, 10], dtype=int32)

In [277]:
a = np.random.normal(0,1,30)
a

array([-0.22912342, -0.13992269, -0.27050421, -0.90082124,  0.73859558,
        0.46762138, -1.12223013,  0.01125988,  0.09022651, -0.23409169,
       -0.6571055 , -0.22487823,  0.12170467, -0.18822022, -0.94734363,
       -0.95629385,  0.37698953, -0.82318641, -1.81639303,  0.53306264,
        0.07652366,  2.06797973,  0.45099784, -2.0112952 ,  0.70244806,
        0.47718366, -1.11457308, -1.62454446,  1.1485877 ,  1.43397117])

In [278]:
np.std(a)

0.923871889382785

In [279]:
np.sum(a)

-4.563374979778406

In [280]:
sum(a)

-4.563374979778405

In [281]:
np.min(a)

-2.0112951991720838

In [282]:
a = np.random.normal(0,1,(3,3))
a

array([[-0.10201598, -0.21160077, -1.46192395],
       [-2.07805139, -0.71117562,  1.65364316],
       [ 0.57559183, -0.27843111, -0.56365836]])

In [284]:
a.sum(axis=1)

array([-1.7755407 , -1.13558385, -0.26649764])

## Array Broadcasting

In [285]:
a = np.array([1,2,3])
b= np.array([1,2,3])
a+b

array([2, 4, 6])

In [299]:
ones = np.ones((3,3)).reshape(-1,3)
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [292]:
a+ones

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [293]:
a=np.arange(3)
a

array([0, 1, 2])

In [295]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [296]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [301]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [303]:
a

array([0, 1, 2])

In [305]:
a+M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [307]:
a = np.arange(3).reshape((3,1))
a

array([[0],
       [1],
       [2]])

In [313]:
b = np.arange(3)
b

array([0, 1, 2])

In [317]:
print(a.shape,b.shape)

(3, 1) (3,)


In [319]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [321]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [324]:
a = np.arange(3)
a

array([0, 1, 2])

In [326]:
print(m.shape,a.shape)

(3, 2) (3,)


In [328]:
# a+m # it will give broadcast error, dimensions don't match

In [329]:
isim = ['ali','veli','secil']
yas = [25,22,66]
boy = [166,177,188]

In [334]:
data = np.zeros(3, dtype={'names':('isim','yas','boy'),
                          'formats':('U10','i4','f8')})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [338]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy
data

array([('ali', 25, 166.), ('veli', 22, 177.), ('secil', 66, 188.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [340]:
data['isim']

array(['ali', 'veli', 'secil'], dtype='<U10')

In [342]:
data[0]

('ali', 25, 166.)

In [343]:
data[data['yas'] < 25]['isim']

array(['veli'], dtype='<U10')