In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])

a*b

array([ 1,  6, 15, 28])

In [3]:
who # shows variables

No variables match your requested type.


# NumPy Arrays

In [7]:
a = np.array([2.6,3.11,58,22,2,5])
type(a)

numpy.ndarray

In [10]:
np.array([2.6,3.,66.7,58,22,2,5], dtype = 'float32')

array([ 2.6,  3. , 66.7, 58. , 22. ,  2. ,  5. ], dtype=float32)

In [14]:
np.zeros(20, dtype=int) # creates an array consisting 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((2,4)) # creates a matris consisting 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((3,3),8) # creates a matris consisting what I gave

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [22]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [24]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [26]:
np.random.normal(0,1,(3,4))

array([[-0.40500539,  0.92393213, -1.271944  ,  0.92551317],
       [-0.97827694, -1.40370826,  0.44844455, -0.16775677],
       [-1.1075825 , -1.74813393,  0.30276062, -2.51095262]])

In [28]:
np.random.randint(0,10, (3,3))

array([[6, 1, 6],
       [7, 6, 4],
       [0, 1, 2]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Forming (Shape Opeations)

In [43]:
a = np.random.randint(0,10, (3,3))
a

array([[6, 0, 2],
       [4, 8, 4],
       [5, 8, 3]])

In [43]:
a = np.random.randint(0,10, (3,3))
a

array([[6, 0, 2],
       [4, 8, 4],
       [5, 8, 3]])

In [42]:
a.shape

(3, 3)

In [44]:
a.ndim # size

2

In [45]:
a = np.random.randint(0,10, (3,3,3))
a

array([[[1, 5, 8],
        [7, 4, 5],
        [7, 3, 3]],

       [[7, 7, 5],
        [2, 1, 0],
        [8, 1, 7]],

       [[3, 9, 6],
        [2, 4, 3],
        [7, 2, 5]]])

In [47]:
a.shape

(3, 3, 3)

In [50]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a = np.array([1,2,3])
b = a.reshape((1,3))

In [57]:
a.ndim

1

In [58]:
b.ndim

2

In [60]:
a[np.newaxis, :] # reshaped 1d array to 2d (vector) - matrix

array([[1, 2, 3]])

In [61]:
a[:,np.newaxis] # column vector

array([[1],
       [2],
       [3]])